services:
  app:
    image: 'spring-boot-app:latest'
    build:
      context: .
    container_name: spring-boot-app
    depends_on:
      - db
    ports:
        - 8084:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fil-session
      - SPRING_DATASOURCE_USERNAME=fil-session
      - SPRING_DATASOURCE_PASSWORD=fil-session
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:17-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=fil-session
      - POSTGRES_PASSWORD=fil-session
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
       - spring-boot-data:/var/lib/postgresql/data

volumes:
    spring-boot-data: