apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      app: spring-boot-app
      environment: production
  template:
    metadata:
      labels:
        tier: backend
        app: spring-boot-app
        environment: production
    spec:
      containers:
        - name: spring-boot-app-trg
          image: /arunstiwari/spring-boot-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    tier: backend
    app: spring-boot-app
    environment: production
